resources:
  - ../../base

images:
  - name: devsecops-api
    newName: ghcr.io/reinebrenda/devsecops-project-api
    newTag: sha-06bdd67

  - name: devsecops-external
    newName: ghcr.io/reinebrenda/devsecops-project-external
    newTag: latest

  - name: devsecops-frontend
    newName: ghcr.io/reinebrenda/devsecops-project-frontend
    newTag: latest
