apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: devsecops-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: LOG_LEVEL
              value: "info"
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: appuser
            - name: DB_PASSWORD
              value: apppassword
            - name: DB_NAME
              value: appdb
            - name: EXTERNAL_SERVICE_URL
              value: http://external-service:4001
