apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
  namespace: devsecops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-api
  namespace: devsecops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-external
  namespace: devsecops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-postgres
  namespace: devsecops
